repos:

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
  - id: codespell
    types_or: [python, javascript, markdown]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: end-of-file-fixer
    exclude: ^tests/data/

- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
  - id: isort
  
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
